export enum UserRole {
  SUPERADMIN = 'SUPERADMIN',
  ADMIN = 'ADMIN',
  TEACHER = 'TEACHER',
  SUPPORT = 'SUPPORT',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  MANAGER = 'MANAGER',
  MARKETING = 'MARKETING',
  SALES = 'SALES',
  FINANCE = 'FINANCE'
}