/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TakeTestTestIdRouteImport } from './routes/take-test.$testId'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTestsRouteImport } from './routes/_app.tests'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppSupportTeachersRouteImport } from './routes/_app.support-teachers'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppSalaryRouteImport } from './routes/_app.salary'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPermissionsRouteImport } from './routes/_app.permissions'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppParentsRouteImport } from './routes/_app.parents'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMarketingRouteImport } from './routes/_app.marketing'
import { Route as AppManagersRouteImport } from './routes/_app.managers'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppGamificationRouteImport } from './routes/_app.gamification'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppDirectionsRouteImport } from './routes/_app.directions'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBranchesRouteImport } from './routes/_app.branches'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app.students.$studentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeTestTestIdRoute = TakeTestTestIdRouteImport.update({
  id: '/take-test/$testId',
  path: '/take-test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTestsRoute = AppTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTeachersRoute = AppSupportTeachersRouteImport.update({
  id: '/support-teachers',
  path: '/support-teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppParentsRoute = AppParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppManagersRoute = AppManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppGamificationRoute = AppGamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectionsRoute = AppDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AppActivityRoute
  '/attendance': typeof AppAttendanceRoute
  '/branches': typeof AppBranchesRoute
  '/dashboard': typeof AppDashboardRoute
  '/directions': typeof AppDirectionsRoute
  '/finance': typeof AppFinanceRoute
  '/gamification': typeof AppGamificationRoute
  '/groups': typeof AppGroupsRoute
  '/hr': typeof AppHrRoute
  '/managers': typeof AppManagersRoute
  '/marketing': typeof AppMarketingRoute
  '/notifications': typeof AppNotificationsRoute
  '/parents': typeof AppParentsRoute
  '/payments': typeof AppPaymentsRoute
  '/permissions': typeof AppPermissionsRoute
  '/profile': typeof AppProfileRoute
  '/salary': typeof AppSalaryRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/support-teachers': typeof AppSupportTeachersRoute
  '/teachers': typeof AppTeachersRoute
  '/tests': typeof AppTestsRoute
  '/users': typeof AppUsersRoute
  '/take-test/$testId': typeof TakeTestTestIdRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activity': typeof AppActivityRoute
  '/attendance': typeof AppAttendanceRoute
  '/branches': typeof AppBranchesRoute
  '/dashboard': typeof AppDashboardRoute
  '/directions': typeof AppDirectionsRoute
  '/finance': typeof AppFinanceRoute
  '/gamification': typeof AppGamificationRoute
  '/groups': typeof AppGroupsRoute
  '/hr': typeof AppHrRoute
  '/managers': typeof AppManagersRoute
  '/marketing': typeof AppMarketingRoute
  '/notifications': typeof AppNotificationsRoute
  '/parents': typeof AppParentsRoute
  '/payments': typeof AppPaymentsRoute
  '/permissions': typeof AppPermissionsRoute
  '/profile': typeof AppProfileRoute
  '/salary': typeof AppSalaryRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/support-teachers': typeof AppSupportTeachersRoute
  '/teachers': typeof AppTeachersRoute
  '/tests': typeof AppTestsRoute
  '/users': typeof AppUsersRoute
  '/take-test/$testId': typeof TakeTestTestIdRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/directions': typeof AppDirectionsRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/gamification': typeof AppGamificationRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/managers': typeof AppManagersRoute
  '/_app/marketing': typeof AppMarketingRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/parents': typeof AppParentsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/salary': typeof AppSalaryRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/support-teachers': typeof AppSupportTeachersRoute
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/tests': typeof AppTestsRoute
  '/_app/users': typeof AppUsersRoute
  '/take-test/$testId': typeof TakeTestTestIdRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/activity'
    | '/attendance'
    | '/branches'
    | '/dashboard'
    | '/directions'
    | '/finance'
    | '/gamification'
    | '/groups'
    | '/hr'
    | '/managers'
    | '/marketing'
    | '/notifications'
    | '/parents'
    | '/payments'
    | '/permissions'
    | '/profile'
    | '/salary'
    | '/sales'
    | '/settings'
    | '/students'
    | '/support-teachers'
    | '/teachers'
    | '/tests'
    | '/users'
    | '/take-test/$testId'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/activity'
    | '/attendance'
    | '/branches'
    | '/dashboard'
    | '/directions'
    | '/finance'
    | '/gamification'
    | '/groups'
    | '/hr'
    | '/managers'
    | '/marketing'
    | '/notifications'
    | '/parents'
    | '/payments'
    | '/permissions'
    | '/profile'
    | '/salary'
    | '/sales'
    | '/settings'
    | '/students'
    | '/support-teachers'
    | '/teachers'
    | '/tests'
    | '/users'
    | '/take-test/$testId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/activity'
    | '/_app/attendance'
    | '/_app/branches'
    | '/_app/dashboard'
    | '/_app/directions'
    | '/_app/finance'
    | '/_app/gamification'
    | '/_app/groups'
    | '/_app/hr'
    | '/_app/managers'
    | '/_app/marketing'
    | '/_app/notifications'
    | '/_app/parents'
    | '/_app/payments'
    | '/_app/permissions'
    | '/_app/profile'
    | '/_app/salary'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/support-teachers'
    | '/_app/teachers'
    | '/_app/tests'
    | '/_app/users'
    | '/take-test/$testId'
    | '/_app/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TakeTestTestIdRoute: typeof TakeTestTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/take-test/$testId': {
      id: '/take-test/$testId'
      path: '/take-test/$testId'
      fullPath: '/take-test/$testId'
      preLoaderRoute: typeof TakeTestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tests': {
      id: '/_app/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof AppTestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support-teachers': {
      id: '/_app/support-teachers'
      path: '/support-teachers'
      fullPath: '/support-teachers'
      preLoaderRoute: typeof AppSupportTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salary': {
      id: '/_app/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parents': {
      id: '/_app/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AppParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/managers': {
      id: '/_app/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof AppManagersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gamification': {
      id: '/_app/gamification'
      path: '/gamification'
      fullPath: '/gamification'
      preLoaderRoute: typeof AppGamificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directions': {
      id: '/_app/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof AppDirectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDirectionsRoute: typeof AppDirectionsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGamificationRoute: typeof AppGamificationRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppHrRoute: typeof AppHrRoute
  AppManagersRoute: typeof AppManagersRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppParentsRoute: typeof AppParentsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppSupportTeachersRoute: typeof AppSupportTeachersRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTestsRoute: typeof AppTestsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDirectionsRoute: AppDirectionsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGamificationRoute: AppGamificationRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppHrRoute: AppHrRoute,
  AppManagersRoute: AppManagersRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppParentsRoute: AppParentsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppSupportTeachersRoute: AppSupportTeachersRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTestsRoute: AppTestsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TakeTestTestIdRoute: TakeTestTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
